---
- name: Reload `udev` Rules
  ansible.builtin.command: "udevadm control --reload-rules"
  become: true
  changed_when: true

- name: Trigger `udev` Rules
  ansible.builtin.command: "udevadm trigger"
  become: true
  changed_when: true
