---

- name: Encrypt a disk listed in host_vars
  tags: [encrypt-disk, disk]
  block:
    - name: Encrypt the disk from host_vars
      ansible.builtin.include_tasks: encrypt_common.yml
      vars:
        target: "{{ disk_to_encrypt }}"
