---

- name: Encrypt partition that is next to the root partition
  tags: [encrypt-partition, disk]
  block:
    - name: Get the root (`/`) partition
      ansible.builtin.command: "findmnt -n -o SOURCE /"
      register: root_partition
      changed_when: false
      become: true

    - name: Extract the disk containing root
      ansible.builtin.set_fact:
        root_disk: "{{ root_partition.stdout | regex_replace('p?[0-9]+$', '') }}"

    - name: Get partition table from `fdisk`
      ansible.builtin.command: "fdisk -l {{ root_disk }}"
      register: fdisk_output
      changed_when: false
      become: true

    - name: Find adjacent partition to root using `fdisk`
      ansible.builtin.set_fact:
        adjacent_partitions: "{{ (fdisk_output.stdout_lines
          | select('search', '^/dev/')
          | reject('search', root_partition.stdout)
          | reject('search', 'EFI System|boot|SWAP|BIOS boot')
          | list) }}"

    - name: Show detected adjacent partitions
      ansible.builtin.debug:
        msg: "Candidate partitions: {{ adjacent_partitions }}"

    - name: Fail if no valid adjacent partition is found
      ansible.builtin.fail:
        msg: "No valid adjacent partition found for encryption."
      when: adjacent_partitions | length == 0

    - name: Select the first available partition
      ansible.builtin.set_fact:
        adjacent_partition: "{{ adjacent_partitions[0] }}"

    - name: Show detected adjacent partition
      ansible.builtin.debug:
        msg: "Adjacent partition to encrypt: {{ adjacent_partition }}"

    - name: Encrypt the partition adjacent to the root
      ansible.builtin.include_tasks: encrypt_common.yml
      vars:
        target: "{{ adjacent_partition }}"
