---

- name: Ensure encryption target exists
  ansible.builtin.stat:
    path: "{{ target }}"
  register: target_check
  become: true

- name: Fail if no valid target is found
  ansible.builtin.fail:
    msg: "No valid target found for encryption."
  when: not target_check.stat.exists or (target is undefined or target | trim == "")

- name: Fail if LUKS password is not set or empty
  ansible.builtin.fail:
    msg: "LUKS_PASSWORD environment variable is not set or empty!"
  when: luks_password is undefined or luks_password | trim | length == 0

- name: Generate LUKS device name
  ansible.builtin.set_fact:
    luks_device: "encrypted_{{ target | regex_replace('/dev/', '') | regex_replace('/', '_') }}"

- name: Generate mount point name
  ansible.builtin.set_fact:
    mount_point: "/mnt/{{ luks_device }}"

- name: Encrypt and open the target with LUKS2
  community.crypto.luks_device:
    device: "{{ target }}"
    state: "opened"
    type: luks2
    passphrase: "{{ luks_password }}"
    name: "{{ luks_device }}"
  become: true
  no_log: true

- name: Format the encrypted target as ext4 (if no filesystem exists)
  community.general.filesystem:
    fstype: ext4
    dev: "/dev/mapper/{{ luks_device }}"
  become: true

- name: Mount the encrypted target (and ensure persistence in /etc/fstab)
  ansible.posix.mount:
    path: "{{ mount_point }}"
    src: "/dev/mapper/{{ luks_device }}"
    fstype: ext4
    opts: defaults
    state: mounted
  become: true

- name: Ensure persistence in /etc/crypttab
  community.general.crypttab:
    name: "{{ luks_device }}"
    backing_device: "/dev/mapper/{{ luks_device }}"
    opts: "luks"
    state: present
  no_log: true
