---

- name: Check for dependencies required for interface renaming
  tags: [rename-interface, network]
  block:
    - name: Ensure required network packages are installed
      ansible.builtin.package:
        name:
          - "{{ 'iproute2' if ansible_os_family == 'Debian' else 'iproute' }}"
          - jq
        state: present
      become: true
