---

- name: Apply CPU governor and C-state settings
  block:
    - name: Apply CPU governor settings
      ansible.builtin.include_tasks: governors.yml
      tags: [governor, cpu]

    - name: Apply CPU C-state settings
      ansible.builtin.include_tasks: cstate.yml
      tags: [cstate, cpu]

  rescue:
    - name: Log failure but continue
      ansible.builtin.debug:
        msg: "Governor settings failed, but continuing with C-state settings."

    - name: Apply CPU C-state settings (even if governor settings failed)
      ansible.builtin.include_tasks: cstate.yml
      tags: [cstate, cpu]
