---

- name: Apply CPU governor settings
  tags: [set-governor, cpu]
  block:
    - name: Apply CPU governor settings
      ansible.builtin.include_tasks: set_governor.yml

  rescue:
    - name: Log failure but continue
      ansible.builtin.debug:
        msg: "[ERROR] Governor settings failed, but continuing with C-state settings."

- name: Apply CPU C-state settings
  ansible.builtin.include_tasks: set_cstates.yml
  tags: [set-cstates, cpu]
